### ISSUE TITLE
Update for 1.0

### ISSUE THREAD

**Issue by loscil06** [jopejope/BillysCaravanFormation#1]
Hello! Is it possible to have this updated for the current version of the game? Cheers.

**Comment by jopejope** [comment]
Updated for 1.0.
Someone else should adopt this mod. It's unlikely I will make future updates.

**Comment by loscil06** [comment]
Wow! Thanks a lot!

**Comment by loscil06** [comment]
By the way, will you update the forum thread to reflect the update?
https://ludeon.com/forums/index.php?topic=33946.msg345931
